# Generated by Django 3.2 on 2021-06-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('capacity', models.BigIntegerField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.country')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('batting_type', models.CharField(max_length=255)),
                ('bowling_type', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.country')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(null=True)),
                ('season', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('innings', models.IntegerField()),
                ('balls', models.FloatField()),
                ('runs_off_bat', models.IntegerField()),
                ('extras', models.IntegerField()),
                ('wides', models.IntegerField()),
                ('noballs', models.IntegerField()),
                ('byes', models.IntegerField()),
                ('legbyes', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('wicket_type', models.CharField(max_length=255, null=True)),
                ('player_dismissed', models.CharField(max_length=255, null=True)),
                ('other_wicket_type', models.CharField(max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('batting_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batting_team', to='match.team')),
                ('bowler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler', to='match.player')),
                ('bowling_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_team', to='match.team')),
                ('non_striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_striker', to='match.player')),
                ('other_player_dismissed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_player_dismisse', to='match.player')),
                ('striker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='striker', to='match.player')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.venue')),
            ],
        ),
    ]
